### ISSUE TITLE
Integration with minimongo

### ISSUE THREAD

**Issue by elie222** [Swydo/blaze-apollo#2]
Are there plans to integrate this with minimongo?

**Comment by jamiter** [comment]
Blaze already integrates with MiniMongo ;) I asume you mean you could load data into MiniMongo via GraphQl subscriptions?

This package focusses on getting GraphQl data into a template. I think other packages should focus on getting data into MiniMongo via GraphQl subscriptions for example.

Once data is in MiniMongo its trivial to load it into Blaze.

Thanks for asking though! A better reactive integration with Blaze would be nice indeed. I believe theres already a package doing something that gets close. If I find it I'll comment here.
